amazonProperties:
  endpointUrl: ${AWS_S3_ENDPOINT}
  accessKey: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  bucketName: ${AWS_S3_BUCKET}
cloud:
 aws:
  stack:
   auto: false
  region:
   static: us-east-1